apiVersion: v1
kind: Service
metadata:
  name: broken-reg
  labels:
    app: broken-reg
spec:
  type: ClusterIP
  ports:
    - port: 443
      protocol: TCP
      name: https
      targetPort: 8080
  selector:
    app: broken-reg
